# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60742feb93fae734c96a3bce87003c5a8f8792ec8d41d8c9da9966e627149f443d33cb7df1e07433f9cceb9e95c9294fcb606612d5a446c9d38cad9175f82620

test:
  secret_key_base: 9e2c83cddac6070fcd847d561be0b3cd0949cfef1acc843149994edf291507ffc984326a5b83960a3ec773f7fe17d77999f03db87550dee519b738b1471b2359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
